FROM node:18-alpine AS build
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY ["package.json", "yarn.lock", "./"]
RUN yarn
COPY . ./
RUN yarn build

EXPOSE 80
CMD ["yarn", "prod"]
